in_channels: 1                  # Input Channels (Fire State)
hidden_dim: 128                 # Hidden dimensions of the model
layers: [2, 2, 4, 2]            # Number of layers in each stage
downscaling_factors: [4, 2, 2, 2]  # Downscaling factors for each stage
heads: [3, 6, 9, 12]            # Number of attention heads
head_dim: 64                    # Dimension per attention head
window_size: [4, 4, 4]          # Window size for attention
dropout: 0.1                    # Dropout rate
relative_pos_embedding: true    # Enable relative positional embedding
num_classes: 1                  # Number of output classes
